# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2 
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - package-id: "Newtonsoft.Json"
        versions: [">=12.0.0, <12.0.3"]
      - package-id: "Microsoft.Extensions.Logging"
        versions: ["<2.2.0"]
